name: Run Python Script

on: push
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python and Chrome
        uses: actions/setup-python@v4 browser-actions/setup-chrome@v1
        with:
          python-version: '3.10.4'
      - name: Run Python Script
        run: 
          chrome --version
          python3 hello.py
