name: Run Python Script

on: push
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
      - name: Run Python Script
        run: 
          pip install --upgrade pip
          pip install -r requirements.txt
          python3 hello.py
